-- cc_websocket_player.lua
-- Connects to websocket + controls the Rc1PCzLH music player

local speaker = peripheral.find("speaker")
if not speaker then
    error("No speaker attached!", 0)
end

-- Load config generated by installer
local config = require("config")
local URL = config.ws_url

print("Connecting to WebSocket:", URL)
local ws, err = http.websocket(URL)

if not ws then
    print("Connection failed:", err)
    return
end

print("CONNECTED — waiting for music commands...")

-- Main loop
while true do
    local msg = ws.receive()

    if msg == nil then break end

    print("[RECEIVED] " .. msg)

    -- We support both plain text + JSON control
    local ok, data = pcall(textutils.unserializeJSON, msg)

    -- If JSON command
    if ok and type(data) == "table" then

        -------- PLAY from URL --------
        if data.action == "play" and data.url then
            print("Starting song:", data.url)
            shell.run("music", data.url)   -- This calls Rc1PCzLH script
            ws.send("PLAYING " .. data.url)

        -------- STOP --------
        elseif data.action == "stop" then
            print("Stopping song...")
            speaker.stop()
            ws.send("STOPPED")

        -------- VOLUME --------
        elseif data.action == "volume" and data.level then
            print("Setting volume:", data.level)
            settings.set("music.volume", data.level)
            ws.send("VOLUME SET TO " .. data.level)
        end

    -- Otherwise fallback to raw text commands ----------------
    else
        if msg == "stop" then
            speaker.stop()
            ws.send("STOPPED")
        end
    end
end

ws.close()
print("WebSocket Closed")
