-- cc_websocket_player.lua
-- Connects to websocket + controls the Rc1PCzLH music player

local speaker = peripheral.find("speaker")
if not speaker then
    error("No speaker attached!", 0)
end

-- Load config generated by installer
local config = require("config")
local URL = config.ws_url

print("Connecting to WebSocket:", URL)
local ws, err = http.websocket(URL)

if not ws then
    print("Connection failed:", err)
    return
end

print("CONNECTED — waiting for music commands...")

-- Main loop
while true do
    local msg = ws.receive()
    if msg == nil then break end

    print("RAW MESSAGE >>>", msg) -- Debug print

    -- Try JSON decode
    local ok, data = pcall(textutils.unserializeJSON, msg)

    if ok and type(data) == "table" then
        print("JSON DECODED >>>", data.action, data.url or data.level)

        if data.action == "play" then
            print("Play command received. Starting music...")
            shell.run("music", data.url)
            ws.send("CC: PLAY STARTED")
        elseif data.action == "stop" then
            print("Stopping...")
            ws.send("CC: STOPPED")
        end

    else
        print("NON-JSON MESSAGE >>>", msg)
    end
end


ws.close()
print("WebSocket Closed")
